# --- Configuración de Base de Datos (Depende 100% de Variables de Entorno) ---
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driverClassName=org.postgresql.Driver

# --- JPA / Hibernate ---
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

# --- URLs de Microservicios (Para la Integración) ---
donaciones.url=${DONACIONES_URL}
entidades.url=${ENTIDADES_URL}
incentivos.url=${INCENTIVOS_URL}

# --- Servidor ---
server.port=${PORT:8080}

# --- Actuator & Métricas ---
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always
management.datadog.metrics.export.enabled=true
management.datadog.metrics.export.api-key=${DD_API_KEY}

# --- Misceláneos ---
spring.devtools.restart.enabled=true
spring.cloud.compatibility-verifier.enabled=false
logging.level.ar.edu.utn.dds.k3003.clients=DEBUG